[package]
name = "ream-rpc-lean"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
actix-web.workspace = true
libp2p.workspace = true
parking_lot.workspace = true
tokio.workspace = true
tracing.workspace = true

#ream-dependencies
ream-api-types-common.workspace = true
ream-api-types-lean.workspace = true
ream-chain-lean.workspace = true
ream-consensus-lean.workspace = true
ream-p2p.workspace = true
ream-rpc-common.workspace = true

[lints]
workspace = true
