[package]
name = "ream-syncer"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
ethereum_ssz.workspace = true
futures.workspace = true
libp2p.workspace = true
libp2p-identity.workspace = true
libp2p-mplex.workspace = true
ream-beacon-chain.workspace = true
ream-bls.workspace = true
tokio.workspace = true
tracing.workspace = true
tree_hash.workspace = true

# ream dependencies
ream-consensus-beacon.workspace = true
ream-consensus-misc.workspace = true
ream-executor.workspace = true
ream-network-spec.workspace = true
ream-p2p.workspace = true
ream-storage.workspace = true
